### PR TITLE
Download option

### PR DESCRIPTION
**Pull request by Anixen**
Implemented/fixed the download result button on the editor page.
It provides the possibility to dowload in the PNG, JPG, TIFF formats; or lets the user keep the orignal input format.

### CODE REVIEW

**Comment by KrisNumber24** [comment]
It works but you should disabled the download button during a render.

**Comment by Anixen** [comment]
I changed the buttons to prevent the user from sending another request from the livedemo while he hasn't received a response from the pending request.

**Comment by Anixen** [comment]
I am currently working on adding a loading icon for the download.

**Comment by KrisNumber24** [comment]
Look good to me :ok:

**Comment by ghost** [comment]
Nice to me :v:

**Pull request merged**
