### PR TITLE
Fix upload plugins

### PR DESCRIPTION
**Pull request by fabiencastan**

### CODE REVIEW

**Comment by Olivier-Daire** [comment]
Doesn't work for me, I still have the same error : 

```
WARNING:root:analyseBundle 56d32e2858f6f20077a56b02 : {'status': 'waiting', 'extraction': 'waiting', 'analyse': 'waiting', 'datas': None}.
WARNING:root:tempFilepath: /tmp/tmpqb1T5w
WARNING:root:LD_LIBRARY_PATH: :/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/lib:/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/lib64
WARNING:root:
WARNING:root:Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/CMakeLists.txt".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/Resources".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/Resources/tuttle.blur.svg".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/Resources/tuttle.png".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/Resources/tuttle.blur.png".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/Resources/tuttle.svg".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src/BlurProcess.hpp".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src/BlurPluginFactory.cpp".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src/BlurPluginFactory.hpp".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src/BlurDefinitions.hpp".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src/mainEntry.cpp".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src/BlurPlugin.hpp".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src/BlurProcess.tcc".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src/BlurPlugin.cpp".
Search plugins recursively in "/usr/OFX/Plugins".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/CMakeLists.txt".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/Resources".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/Resources/tuttle.blur.svg".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/Resources/tuttle.png".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/Resources/tuttle.blur.png".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/Resources/tuttle.svg".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src/BlurProcess.hpp".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src/BlurPluginFactory.cpp".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src/BlurPluginFactory.hpp".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src/BlurDefinitions.hpp".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src/mainEntry.cpp".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src/BlurPlugin.hpp".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src/BlurProcess.tcc".
Search plugins recursively in "/opt/shuttleofx/analyser/56d32e2858f6f20077a56b02/Blur/src/BlurPlugin.cpp".
WARNING:root:pluginCache: OfxhPluginCache {
No Plug-ins Found.
________________________________________________________________________________
}

WARNING:root:Analyse plugins: /opt/shuttleofx/analyser/56d32e2858f6f20077a56b02
WARNING:root:Nb plugins: 0
```

Did I miss something ?

**Comment by fabiencastan** [comment]
It seems that there is no plugin binary (*.ofx.bundle) in your archive but only the source code of the plugin.

**Comment by Olivier-Daire** [comment]
Works for me :smile:

**Comment by Olivier-Daire** [comment]
@Anixen @KrisNumber24 @LoRayZm Can one of you test this PR please ? It's a core feature and I really want to be sure that everything is ok for everyone when uploading a bundle, thank's

**Pull request merged**
