### PR TITLE
Image from url

### PR DESCRIPTION
**Pull request by KrisNumber24**
connected to #86
connected to #87

### CODE REVIEW

**Comment by KrisNumber24** [comment]
:warning: Need to change render.cfg to add [TMP] section. It's exactly the same section that [CACHE] section but with TMP as title.

**Comment by KrisNumber24** [comment]
For more details read the file render.cfg in etc in the shuttleOFX repository.

**Comment by Olivier-Daire** [comment]
:+1:

**Comment by KrisNumber24** [comment]
:warning: Need to create tmp folder in /opt/shuttleofx/render/resources/ python doesn't create it automatically !

**Comment by KrisNumber24** [comment]
Need to clean some files and to rename some functions ! Before to merge send me a message
:white_check_mark: **DONE**

**Comment by ghost** [comment]
Nice ! :+1:

**Comment by ghost** [comment]
Ok for me ;o

**Pull request merged**
